services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: vnic-livekit
    restart: unless-stopped
    ports:
      - "7880:7880" # WebRTC
      - "7881:7881" # HTTP
    environment:
      - "LIVEKIT_KEYS=genation-lk: genation-lk-vnic"
    command: --dev --node-ip=host.docker.internal

  neo4j:
    image: neo4j:latest
    container_name: vnic-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/genation-vnic
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
